version: "3.8"

networks:
  postgres-compose-network:
    driver: bridge

services:
  postgres:
    image: postgres:14
    container_name: postgres_ng_cash_db
    environment:
      POSTGRES_PASSWORD: 123456
    restart: always
    volumes: 
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4:6.14
    container_name: postgres_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 8080
    restart: always
    volumes:
     - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

  api:
    image: node:16
    container_name: api_container
    working_dir: /usr/src/tech_challenge_ng_cash
    command: bash -c "npm install --omit=dev && npm start"
    restart: always
    volumes: 
      - ./dist/:/usr/src/tech_challenge_ng_cash/dist
      - ./package.json:/usr/src/tech_challenge_ng_cash/package.json
      - ./.env:/usr/src/tech_challenge_ng_cash/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    
