version: "3.8"

networks:
  postgres-compose-network:
    driver: bridge

services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfiles/PostgreSQL/Dockerfile
    image: ng_cash_db
    container_name: postgres_ng_cash_db
    environment:
      POSTGRES_PASSWORD: 123456
    restart: always
    volumes: 
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    build: 
      context: .
      dockerfile: Dockerfiles/PGAdmin/Dockerfile
    image: pgadmin
    container_name: postgres_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 8080
    restart: always
    volumes:
     - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

  api:
    build:
      context: .
      dockerfile: Dockerfiles/API-CI/Dockerfile
    image: tech_challenge_api
    container_name: api_container
    command: npm start
    restart: always
    volumes: 
      - ./dist:/usr/src/tech_challenge_ng_cash/dist
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
    
