version: "3.8"

networks:
  postgres-compose-network:
    driver: bridge

services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfiles/PostgreSQL/Dockerfile
    image: ng_cash_db
    container_name: postgres_ng_cash_db
    environment:
      POSTGRES_PASSWORD: 123456
    restart: always
    volumes: 
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
